### ISSUE TITLE
那个版本的py啊 换了几个版本都不可以

### ISSUE THREAD

**Issue by tdd1048** [ZDZX-T/cardRecorder#2]
C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe C:\Users\Administrator\Downloads\Compressed\cardRecorder-master\cardRecorder-master\GUI.py 

C:\Users\Administrator\Downloads\Compressed\cardRecorder-master\cardRecorder-master\GUI.py:253: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  t.setDaemon(True)
Exception in thread Thread-1 (startRecord):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Downloads\Compressed\cardRecorder-master\cardRecorder-master\GUI.py", line 265, in startRecord
    findMyCards()
  File "C:\Users\Administrator\Downloads\Compressed\cardRecorder-master\cardRecorder-master\GUI.py", line 160, in findMyCards
    img = pyautogui.screenshot(region=myPos)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.

进程已结束，退出代码为 0

**Comment by ZDZX-T** [comment]
去网上查了下“pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.”的报错信息，貌似是因为没有安装pyscreeze的包，可以试试pip install pyscreeze，如果不行的话就得自己找下解决方法了。有新的报错也可以拿来讨论。
